AllCops:
  Exclude:
    - Gemfile
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'Rakefile'
Style/FrozenStringLiteralComment:
   Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
Style/SymbolArray:
  Enabled: false